spring:
  application:
    name: event-ticketing-system
  datasource:
    url: jdbc:h2:mem:ticketdb
    driver-class-name: org.h2.Driver
    username: sa
    password: null
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
ticketing:
  totalTickets: 300
  ticketReleaseRate: 1
  customerRetrievalRate: 2000
  maxTicketCapacity: 15
logging:
  level:
    com.ticketing: INFO
